"""pin the daily wird

Revision ID: 76be43b4c3f2
Revises: b258055a48ee
Create Date: 2026-09-06 22:54:09.284739
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '76be43b4c3f2'
down_revision: str | None = 'b258055a48ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not cosmetic: without it the rebuilt table
    # would take NULL for every existing group and the NOT NULL check would
    # fail. Groups that predate pinning get it switched on, which is the
    # default for new groups too.
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pin_wird', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('pin_wird')

    # ### end Alembic commands ###
