"""init schema

Revision ID: b258055a48ee
Revises: 
Create Date: 2026-09-06 17:57:51.049832
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'b258055a48ee'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayahs',
    sa.Column('surah', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('hizb', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('surah', 'number', name=op.f('pk_ayahs'))
    )
    with op.batch_alter_table('ayahs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ayahs_page_no'), ['page_no'], unique=False)

    op.create_table('badges',
    sa.Column('chat_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('badge', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=32), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', 'badge', 'ref', name=op.f('pk_badges'))
    )
    op.create_table('groups',
    sa.Column('chat_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('pages_per_day', sa.Integer(), nullable=False),
    sa.Column('active_weekdays', sa.JSON(), nullable=False),
    sa.Column('send_time', sa.Time(), nullable=False),
    sa.Column('first_reminder_after_hours', sa.Integer(), nullable=False),
    sa.Column('reminder_interval_hours', sa.Integer(), nullable=False),
    sa.Column('reminder_max_count', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('mentions_per_message', sa.Integer(), nullable=False),
    sa.Column('day_close_time', sa.Time(), nullable=False),
    sa.Column('advance_rule', sa.String(length=16), nullable=False),
    sa.Column('weekly_report_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_report_weekday', sa.Integer(), nullable=False),
    sa.Column('weekly_report_time', sa.Time(), nullable=False),
    sa.Column('week_start_weekday', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('khatmah_number', sa.Integer(), nullable=False),
    sa.Column('khatmah_started_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_groups'))
    )
    op.create_table('nudges',
    sa.Column('chat_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('last_nudged_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_nudges'))
    )
    op.create_table('page_index',
    sa.Column('page_no', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('juz', sa.Integer(), nullable=False),
    sa.Column('hizb', sa.Integer(), nullable=False),
    sa.Column('first_surah', sa.Integer(), nullable=False),
    sa.Column('first_ayah', sa.Integer(), nullable=False),
    sa.Column('last_surah', sa.Integer(), nullable=False),
    sa.Column('last_ayah', sa.Integer(), nullable=False),
    sa.Column('surah_names', sa.String(length=256), nullable=False),
    sa.Column('ayah_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('page_no', name=op.f('pk_page_index'))
    )
    op.create_table('page_media',
    sa.Column('page_no', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('file_unique_id', sa.String(length=128), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('page_no', name=op.f('pk_page_media'))
    )
    op.create_table('surahs',
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=False),
    sa.Column('ayah_count', sa.Integer(), nullable=False),
    sa.Column('first_page', sa.Integer(), nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number', name=op.f('pk_surahs'))
    )
    op.create_table('user_stats',
    sa.Column('chat_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('total_done', sa.Integer(), nullable=False),
    sa.Column('total_missed', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('consecutive_missed', sa.Integer(), nullable=False),
    sa.Column('last_done_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_user_stats'))
    )
    op.create_table('daily_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('album_message_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_repeat_of', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], name=op.f('fk_daily_tasks_chat_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['is_repeat_of'], ['daily_tasks.id'], name=op.f('fk_daily_tasks_is_repeat_of_daily_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_tasks')),
    sa.UniqueConstraint('chat_id', 'task_date', name='uq_daily_tasks_chat_id')
    )
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_tasks_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index('ix_daily_tasks_status', ['chat_id', 'status'], unique=False)

    op.create_table('subscribers',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], name=op.f('fk_subscribers_chat_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_subscribers'))
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index('ix_subscribers_active', ['chat_id', 'is_active'], unique=False)

    op.create_table('weekly_reports',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('active_days', sa.Integer(), nullable=False),
    sa.Column('perfect_user_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], name=op.f('fk_weekly_reports_chat_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'week_start', name=op.f('pk_weekly_reports'))
    )
    op.create_table('completions',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('was_subscriber', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['daily_tasks.id'], name=op.f('fk_completions_task_id_daily_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id', name=op.f('pk_completions'))
    )
    op.create_table('reminder_log',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('message_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['daily_tasks.id'], name=op.f('fk_reminder_log_task_id_daily_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'seq', name=op.f('pk_reminder_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_log')
    op.drop_table('completions')
    op.drop_table('weekly_reports')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index('ix_subscribers_active')

    op.drop_table('subscribers')
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_tasks_status')
        batch_op.drop_index(batch_op.f('ix_daily_tasks_chat_id'))

    op.drop_table('daily_tasks')
    op.drop_table('user_stats')
    op.drop_table('surahs')
    op.drop_table('page_media')
    op.drop_table('page_index')
    op.drop_table('nudges')
    op.drop_table('groups')
    op.drop_table('badges')
    with op.batch_alter_table('ayahs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ayahs_page_no'))

    op.drop_table('ayahs')
    # ### end Alembic commands ###
